### ISSUE TITLE
 throw er; // Unhandled 'error' event

### ISSUE THREAD

**Issue by forging2012** [eggjs-community/generator-eggjs#17]
```
➜  eggjs yo eggjs generator-eggjs-demo

     _-----_     ╭──────────────────────────╮
    |       |    │    Welcome to the epic   │
    |--(o)--|    │      generator-eggjs     │
   `---------´   │        generator!        │
    ( _´U`_ )    ╰──────────────────────────╯
    /___A___\   /
     |  ~  |     
   __'.___.'__   
 ´   `  |° ´ Y ` 

? project type simple
? project name generator-eggjs-demo
? project description None
? project author admin
? project keys 220309e7c84012fa9599439dcd2fb634d872d77d
identical .gitignore
identical package.json
identical app/controller/home.js
identical app/router.js
 conflict config/config.default.js
? Overwrite config/config.default.js? overwrite
    force config/config.default.js
identical config/plugin.js
identical Dockerfile
identical README.md
identical README.zh-CN.md
identical test/app/controller/home.test.js
events.js:174
      throw er; // Unhandled 'error' event
      ^

Error [ERR_STREAM_WRITE_AFTER_END]: write after end
    at writeAfterEnd (_stream_writable.js:248:12)
    at Transform.Writable.write (_stream_writable.js:296:5)
    at DestroyableTransform.ondata (/usr/local/lib/node_modules/generator-eggjs/node_modules/readable-stream/lib/_stream_readable.js:619:20)
    at DestroyableTransform.emit (events.js:198:13)
    at addChunk (/usr/local/lib/node_modules/generator-eggjs/node_modules/readable-stream/lib/_stream_readable.js:291:12)
    at readableAddChunk (/usr/local/lib/node_modules/generator-eggjs/node_modules/readable-stream/lib/_stream_readable.js:278:11)
    at DestroyableTransform.Readable.push (/usr/local/lib/node_modules/generator-eggjs/node_modules/readable-stream/lib/_stream_readable.js:245:10)
    at DestroyableTransform.Transform.push (/usr/local/lib/node_modules/generator-eggjs/node_modules/readable-stream/lib/_stream_transform.js:148:32)
    at DestroyableTransform._transform (/usr/local/lib/node_modules/generator-eggjs/node_modules/mem-fs-editor/lib/actions/commit.js:34:12)
    at DestroyableTransform.Transform._read (/usr/local/lib/node_modules/generator-eggjs/node_modules/readable-stream/lib/_stream_transform.js:184:10)
Emitted 'error' event at:
    at Transform.onerror (/usr/local/lib/node_modules/generator-eggjs/node_modules/readable-stream/lib/_stream_readable.js:640:52)
    at Transform.emit (events.js:198:13)
    at errorOrDestroy (internal/streams/destroy.js:107:12)
    at writeAfterEnd (_stream_writable.js:250:3)
    at Transform.Writable.write (_stream_writable.js:296:5)
    [... lines matching original stack trace ...]
    at DestroyableTransform.Readable.push (/usr/local/lib/node_modules/generator-eggjs/node_modules/readable-stream/lib/_stream_readable.js:245:10)

```

**Comment by pandaTerminator** [comment]
There's something wrong about dependencies about "gulp-rename".  [issue link](https://github.com/hparra/gulp-rename/issues/84). Upgrade this package to v2.0.0 maybe can help you. It works for me.
